spring.application.name=reservas-service
server.port=8082

spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.servlet.UserDetailsServiceAutoConfiguration

spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.show-sql=true

# Cognito valida el JWT via este issuer (Spring Security descarga las llaves publicas solo, via JWKS)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}